project_id = "interact"

[functions.create-session]
verify_jwt = false

[functions.participant-action]
verify_jwt = false

[functions.presenter-action]
verify_jwt = false

[functions.ai-exit-ticket-summary]
verify_jwt = false

[functions.ai-screen-preview]
verify_jwt = false

[functions.ai-short-answer-summary]
verify_jwt = false

[functions.analyze-question]
verify_jwt = false

[functions.analyze-session]
verify_jwt = false

[functions.generate-exit-ticket]
verify_jwt = false

[functions.shorten-url]
verify_jwt = false
